name: "auto-tag-latest"
on:
  workflow_dispatch:
  release:
jobs:
  auto-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git push --delete origin latest
          git tag latest master
          git push origin latest
