name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
    types:
      [ opened, synchronize, reopened ]
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - uses: ./
      with:
        addons: ingress

    # Test that nginx ingress has been enabled
    - run: |
        minikube addons list | grep 'ingress ' | grep enabled
  test-extraOptions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./
        with:
          extra-config: 'kubelet.max-pods=10'

      # Test that minikube max-pods extraConfig has been set
      - run: |
          cat ~/.minikube/profiles/minikube/config.json | jq '.KubernetesConfig.ExtraOptions[0].Key' | grep max-pods
